#!/bin/bash

TEMPLATE=type.f.in

TYPE=$1
PARENT=$2

echo "> $TYPE.f with parent $PARENT"

if [ -z $PARENT ]; then
   echo no parent
   sed -e "s/TYPE/${TYPE}/g" \
      -e "/[sg]et_size_f/d" \
      -e "/PARENT/Id" $TEMPLATE > $TYPE.f
else
   sed -e "s/TYPE/${TYPE}/g"\
      -e "/tcreate_f/d" \
      -e "s/PARENT/${PARENT}/g" $TEMPLATE > $TYPE.f
fi
